### ISSUE TITLE
XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by brandonros** [RappidDevelopment/quickbooks-js#15]
```
This page contains the following errors:

error on line 14 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.
```

Trying to access the WSDL in the browser. Maybe that's a bad idea?

Running QBWC says "No data exchange required" which seems positive, but I see no logged events on the server output either.

**Comment by mattmorgis** [comment]
Hi @brandonros, not sure why you'd want to access in a browser, what are you trying to accomplish by doing that? 

Are you running this from the command line or including it in an express.js application? 

If you have granted access to your QBWC application and correctly set your environment variables, you should see the `No data exchange required` and this line in the QBWC log file:

```
Received from authenticate() following parameters:<authRet[0]="some-generic-guid">  
<authRet[1]="NONE"><authRet[2]=""><authRet[3]="">
```

I'm still pecking away at this module to get it to `1.0.0`. Once I complete #12, I'll be at that point (hopefully within the next day or two). Basically what is happening is your QBWC is correctly connecting to your SOAP service, but it's not sending any `qbXML` commands to run, it's simply saying there [is nothing in the queue](https://github.com/RappidDevelopment/quickbooks-js/blob/master/lib/web-service.js#L172). #12 will give you the ability to pass in `qbXML` commands and handle responses. 

I also have no logging configured yet in this. Issue #16 speaks to that, and will give you the ability to set different logging levels as needed. 

Let me know if you have any other issues or questions?

**Comment by mattmorgis** [comment]
Hi @brandonros,

I finished #12 and updated the `README` with an example [qbXMLHandler](https://github.com/RappidDevelopment/quickbooks-js/blob/master/bin/qbXMLHandler/index.js) class that can send and receive the `qbXML` requests and responses. 

Let me know if you have any questions or issues going forward, but I have now fully integrated this with one of my websites. I'll leave this open for another day or two and close it if I don't hear from ya. 

Cheers 🍻

**Comment by mattmorgis** [comment]
I'm going to close this since it's been about 2 weeks since I've last heard from you. Please open up another issue if you have any other questions!
